### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/perceptar/pilot

This was requested by a real person (user jazztropist) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by ninabreznik** [comment]
@serapath I think this can be deleted, right?

**Comment by serapath** [comment]
yes

**Comment by serapath** [comment]
can you close this?

**Comment by ninabreznik** [comment]
Nope. How did it even get here?

**Comment by dedesatori** [comment]
It was an experiment I was using to learn. I am closing this

**Comment by ninabreznik** [comment]
Ok, interesting. So it was "hosted task" from your waffle board... Thanks for helping us figure that out :)

**Pull request closed without merging**
